spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web.filter: debug
    com.ff: debug

ff:
  scrap:
    yahoo:
      url: https://query1.finance.yahoo.com/v8/finance/
feign:
  client:
    szs:
      connectionTimeout: 20000
      readTimeout: 25000
      loggerLevel: full
